FROM node:16-alpine

WORKDIR /app

COPY package.json ./
COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

RUN npm install

COPY . . 


RUN chmod +x /entrypoint.sh


CMD ["npm","run","dev"]