version: '3.8'
services:
  postgres: 
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: "db"

  redis: 
    image: redis:latest
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev 

    volumes:
      - /app/node_modules
      - ./server:/app 

    environment:
     - REDIS_HOST=redis
     - REDIS_PORT=6379
     - PG_USER=postgres
     - PG_HOST=postgres
     - PG_DATABASE=postgres
     - PG_PASSWORD=postgres_password
     - PG_PORT=5432

